/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Terabitia */

#ifndef _Included_Terabitia
#define _Included_Terabitia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Terabitia
 * Method:    Setup
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_Terabitia_Setup
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     Terabitia
 * Method:    cryptAES
 * Signature: ([B[B[B[B)V
 */
JNIEXPORT void JNICALL Java_Terabitia_cryptAES
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
